Add OnFailureSchedulerCallback
allure-framework/allure-cucumberjvm pull request #42
Opened 2017-02-09 04:55 UTC by clicman

In reaction to #41 

Now it is possible to set failure callback in ```@Before``` method which will filre in case of test failed.
Usage example:

**Callback implementation**
```java
public class FailureCallback implements OnFailureCallback {
    @Override
    public Object call() {
        return 10;
    }
}
```

**Usage**

```java
import cucumber.api.java.After;
import cucumber.api.java.Before;

public calss StepDefinitions {
   @Before
    public void before() {
        AllureReporter.applyFailureCallback(FailureCallback.class);
    }

    @After
    public void after() {
        int result = AllureReporter.getFailureCallbackResult();
        Assert.assertEquals(10, result);
    }
}
```

So you can do everything tou want in call(method): attach screenshots, rotate logs, etc. And you always can get callback result in @After section

2017-02-09 11:38 UTC, baev requested changes

2017-02-09 11:38 UTC, baev commented on src/main/java/ru/yandex/qatools/allure/cucumberjvm/AllureReporter.java
> +                if (callback != null) {
can we reduce complexity?

2017-02-09 12:18 UTC, baev commented
By the way, allure2 supports fixtures, so we actually can support steps and attachments in `@Before` & `@After` methods

2017-02-10 03:38 UTC, clicman commented on src/main/java/ru/yandex/qatools/allure/cucumberjvm/AllureReporter.java
> +                if (callback != null) {
Done

2017-02-16 15:56 UTC, baev approved these changes

2017-02-16 15:56 UTC, merged

2017-02-16 15:57 UTC, baev commented
@clicman should I release a new version?

2017-02-16 15:58 UTC, clicman commented
Yes. It is ready for 1.6.2. I'm writing release notes right now.